language: perl
install: export LDLOADLIBS=-lstdc++
script: perl ./Build.PL
perl:
  - "5.14"
  - "5.18"
  - "5.20"
branches:
  only:
    - master
    - stable
sudo: false
cache:
  apt: true
  directories:
    - local-lib
addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - libboost-thread1.55-dev
    - libboost-system1.55-dev
    - libboost-filesystem1.55-dev
    - liblocal-lib-perl
    - g++-4.9
env: CC=g++-4.9
